name: 'publish go'
description: 'Pushes go code to the sdk repo'
inputs:
  repository-token:
    description: token for git authentication
    required: true
  mode:
    description: supported values are 'release' and 'dry-run'
    required: true

runs:
  using: 'composite'
  steps:
   
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.23

    - name: Attempt Build
      working-directory: codegen/go
      shell: bash
      env:
        TOKEN: ${{ inputs.repository-token }}
      run: |
        go get -v -t -d ./...
        go build -v ./...

    - uses: actions/checkout@v4
      with:
        repository: utxorpc/go-codegen
        fetch-depth: 0
        token: ${{ inputs.repository-token }}
        path: go-codegen

    - name: Copy new spec
      shell: bash
      run: |
        rm -Rf go-codegen/utxorpc
        mv codegen/go/* go-codegen/

    - name: Publish
      if: inputs.mode == 'release'
      shell: bash
      run: |
        cd go-codegen
        RELEASE_VERSION=${GITHUB_REF#refs/*/}
        git config --global --add safe.directory `pwd -P`
        git config --global user.email "wolf31o2@blinklabs.io"
        git config --global user.name "Chris Gianelloni (bot)"
        git add .
        git commit --allow-empty -m "GHA: automatic publish: ${RELEASE_VERSION}"
        git push origin HEAD:main
        if [[ ${RELEASE_VERSION} == v* ]]; then
          git tag ${RELEASE_VERSION}
          git push origin ${RELEASE_VERSION}
        fi
